### ISSUE TITLE
inputDirectory doesn't support URL's as well as Swagger2markup does

### ISSUE THREAD

**Issue by zucher** [Swagger2Markup/swagger2markup-maven-plugin#2]
Hi,
in the context of generation from a server endpoint, the constraint File on inputDirectory doesn't allow to specify an URL instead or filesystem

thanks

zucher

**Comment by redowl** [comment]
Sorry for the late response...

Fair point, but supporting URL for inputDirectory isn't as trivial as swapping out file with URI or URL.  For example, if you were trying to use an "http" url, HTTP doesn't provide any mechanism for "listing" files, so your server would have to meet several conditions to be able to locate any resource files, and even then you'd either have to have your server produce DOM or JSON listings and then parse/traverse them that way.  See this SO post for more discussion/better enumeration of issues: http://stackoverflow.com/questions/11561608/how-to-get-list-of-files-directories-of-an-directory-url-in-java

For this reason (both the amount of work and limited functionality it would buy due to server constraints), I don't plan on working on this, nor do I see a clear, generic solution that wouldn't require customization from server to server.

If there is a use case that I'm missing that better enumerates a more simple use case, I'd be happy to revisit discussion.

**Comment by Bricklou** [comment]
Hi redowi,

as stand alone use of Swagger2MarkupConverter converter calls the from methods allows to use URL instead of files, and it's fine working, using a startswith method to discriminate between a file entry of web entry is in this case quite simple, no needs to enumerate.

zucher

**Comment by zucher** [comment]
Hi redowi,

as stand alone use of Swagger2MarkupConverter converter calls the from methods allows to use URL instead of files, and it's fine working, using a startswith method to discriminate between a file entry of web entry is in this case quite simple, no needs to enumerate.

zucher

**Comment by RobWin** [comment]
PR is merged.

**Comment by zucher** [comment]
tks, when are you plan to propose a new version ?

**Comment by RobWin** [comment]
Unfortunately #9 hinders me.
I have to check how to create the Maven Plugin `plugin.xml` with Gradle.

**Comment by zucher** [comment]
ok thank you :-)

**Comment by RobWin** [comment]
If you use Swagger2Markup, if would love to get your GitHub star in the core project :)

**Comment by zucher** [comment]
Done

**Comment by RobWin** [comment]
Thx, but I mean https://github.com/Swagger2Markup/swagger2markup :)

**Comment by zucher** [comment]
On 02/12/2015 16:20, Robert Winkler wrote:
>
> Thx, but I mean https://github.com/Swagger2Markup/swagger2markup :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Swagger2Markup/swagger2markup-maven-plugin/issues/2#issuecomment-161330062>.
>
;-)
